from PyQt5 import QtCore, QtGui, QtWidgets
import sys, os

services = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
sys.path.append(os.path.join(services, 'services'))
from services.change_window import Commands

class Ui_Form(object):

    def buttons(self, Form):

        self.Botao_principal = QtWidgets.QPushButton(Form)
        self.Botao_principal.setEnabled(True)
        self.Botao_principal.setGeometry(QtCore.QRect(10, 260, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Botao_principal.setFont(font)
        self.Botao_principal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Botao_principal.setMouseTracking(False)
        self.Botao_principal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Botao_principal.setCheckable(False)
        self.Botao_principal.setAutoExclusive(False)
        self.Botao_principal.setAutoDefault(False)
        self.Botao_principal.setDefault(False)
        self.Botao_principal.setFlat(False)
        self.Botao_principal.setObjectName("Botao_principal")
        self.Botao_principal_2 = QtWidgets.QPushButton(Form)
        self.Botao_principal_2.setEnabled(True)
        self.Botao_principal_2.setGeometry(QtCore.QRect(10, 340, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Botao_principal_2.setFont(font)
        self.Botao_principal_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Botao_principal_2.setMouseTracking(False)
        self.Botao_principal_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Botao_principal_2.setCheckable(False)
        self.Botao_principal_2.setAutoExclusive(False)
        self.Botao_principal_2.setAutoDefault(False)
        self.Botao_principal_2.setDefault(False)
        self.Botao_principal_2.setFlat(False)
        self.Botao_principal_2.setObjectName("Botao_principal_2")
        self.Botao_principal_3 = QtWidgets.QPushButton(Form)
        self.Botao_principal_3.setEnabled(True)
        self.Botao_principal_3.setGeometry(QtCore.QRect(10, 420, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Botao_principal_3.setFont(font)
        self.Botao_principal_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Botao_principal_3.setMouseTracking(False)
        self.Botao_principal_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Botao_principal_3.setCheckable(False)
        self.Botao_principal_3.setAutoExclusive(False)
        self.Botao_principal_3.setAutoDefault(False)
        self.Botao_principal_3.setDefault(False)
        self.Botao_principal_3.setFlat(False)
        self.Botao_principal_3.setObjectName("Botao_principal_3")
        self.Botao_principal_4 = QtWidgets.QPushButton(Form)
        self.Botao_principal_4.setEnabled(True)
        self.Botao_principal_4.setGeometry(QtCore.QRect(10, 500, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Botao_principal_4.setFont(font)
        self.Botao_principal_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Botao_principal_4.setMouseTracking(False)
        self.Botao_principal_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Botao_principal_4.setCheckable(False)
        self.Botao_principal_4.setAutoExclusive(False)
        self.Botao_principal_4.setAutoDefault(False)
        self.Botao_principal_4.setDefault(False)
        self.Botao_principal_4.setFlat(False)
        self.Botao_principal_4.setObjectName("Botao_principal_4")
        self.Botao_principal_5 = QtWidgets.QPushButton(Form)
        self.Botao_principal_5.setEnabled(True)
        self.Botao_principal_5.setGeometry(QtCore.QRect(10, 580, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.Botao_principal_5.setFont(font)
        self.Botao_principal_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Botao_principal_5.setMouseTracking(False)
        self.Botao_principal_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Botao_principal_5.setCheckable(False)
        self.Botao_principal_5.setAutoExclusive(False)
        self.Botao_principal_5.setAutoDefault(False)
        self.Botao_principal_5.setDefault(False)
        self.Botao_principal_5.setFlat(False)
        self.Botao_principal_5.setObjectName("Botao_principal_5")

    def setupUi(self, Form):

        Form.setObjectName("JANELA INICIAL")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(1920, 1040)
        Form.setMinimumSize(QtCore.QSize(1920, 1040))
        Form.setMouseTracking(False)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(329, -10, 1601, 1061))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.welcome = QtWidgets.QLabel(self.frame)
        self.welcome.setGeometry(QtCore.QRect(550, 110, 751, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")

        self.inicialpagina = QtWidgets.QLabel(self.frame)
        self.inicialpagina.setGeometry(QtCore.QRect(670, 210, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.inicialpagina.setFont(font)
        self.inicialpagina.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inicialpagina.setAlignment(QtCore.Qt.AlignCenter)
        self.inicialpagina.setObjectName("inicialpagina")

        self.graphic = QtWidgets.QWidget(self.frame)
        self.graphic.setGeometry(QtCore.QRect(460, 370, 321, 241))
        self.graphic.setObjectName("graphic")
        self.textgraphic = QtWidgets.QLabel(self.graphic)
        self.textgraphic.setGeometry(QtCore.QRect(0, 0, 321, 241))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textgraphic.setFont(font)
        self.textgraphic.setAlignment(QtCore.Qt.AlignCenter)
        self.textgraphic.setObjectName("texto")

        self.register_product = QtWidgets.QWidget(self.frame)
        self.register_product.setGeometry(QtCore.QRect(460, 710, 321, 241))
        self.register_product.setObjectName("register_product")

        self.clients_widget = QtWidgets.QWidget(self.frame)
        self.clients_widget.setGeometry(QtCore.QRect(1060, 370, 321, 241))
        self.clients_widget.setObjectName("clients_widget")

        self.alertas_widget = QtWidgets.QWidget(self.frame)
        self.alertas_widget.setGeometry(QtCore.QRect(1060, 710, 321, 241))
        self.alertas_widget.setObjectName("alertas_widget")

        self.buttons(Form)
        comandos = Commands(self)
        comandos.event_button()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "JANELA INICIAL"))
        Form.setStyleSheet(_translate("Form", "background-color: #FFF8DC"))

        self.frame.setStyleSheet(_translate("Form", "background-color: white;"))

        self.Botao_principal.setText(_translate("Form", "Principal"))
        self.Botao_principal.setStyleSheet(_translate("Form", "background-color: white;"))

        self.Botao_principal_2.setText(_translate("Form", "Vendas"))
        self.Botao_principal_2.setStyleSheet(_translate("Form", "background-color: white;"))

        self.Botao_principal_3.setText(_translate("Form", "Estoque"))
        self.Botao_principal_3.setStyleSheet(_translate("Form", "background-color: white;"))

        self.Botao_principal_4.setText(_translate("Form", "Registro de Produto"))
        self.Botao_principal_4.setStyleSheet(_translate("Form", "background-color: white;"))

        self.Botao_principal_5.setText(_translate("Form", "Clientes"))
        self.Botao_principal_5.setStyleSheet(_translate("Form", "background-color: white;"))

        self.graphic.setStyleSheet(_translate("Form", "background-color: green;"))
        self.register_product.setStyleSheet(_translate("Form", "background-color: green;"))
        self.clients_widget.setStyleSheet(_translate("Form", "background-color: green;"))
        self.alertas_widget.setStyleSheet(_translate("Form", "background-color: green;"))

        self.welcome.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">BEM-VINDO(A) AO SOFTWARE</span></p></body></html>"))
        self.inicialpagina.setText(_translate("Form", "PAGINA INICIAL"))

